### ISSUE TITLE
An exception is thrown when receiving map data

### ISSUE THREAD

**Issue by david-benes** [yardik/MapSharingMadeEasy#3]
When a user standing next to you sends map data, data appear in my console.
Then an exception is thrown and no 'Accept data' message is shown.

I will provide the exact exception later.
The exception is about reaching the mesh size in Unity.

I can send my data without problems but I am unable to receive map data.

**Comment by yardik** [comment]
What version are you both running? This will definitely happen if you have incompatible map  share versions.

**Comment by yardik** [comment]
no more details, closing
