### ISSUE TITLE
Piece being added to Items list

### ISSUE THREAD

**Issue by RandyKnapp** [yardik/MapSharingMadeEasy#4]
https://github.com/yardik/MapSharingMadeEasy/blob/9a3334a2401830d01ed58c7792582948f60b637b/Patches/ObjectDB.cs#L26

So this is a prefab for a piece, not an item, but it's being added to the items list in ObjectDB. Anything that tries to look it up or spawn an item with this ID will break, because things will try to look for an ItemDrop component on the prefab.

**Comment by yardik** [comment]
Oh - I didn't realize that pieces were not also being added to the ObjectDB! I'll take a look at this. Thanks Randy.

**Comment by yardik** [comment]
fixed
