### ISSUE TITLE
Unintentionally renaming prefab

### ISSUE THREAD

**Issue by RandyKnapp** [yardik/MapSharingMadeEasy#5]
https://github.com/yardik/MapSharingMadeEasy/blob/9a3334a2401830d01ed58c7792582948f60b637b/MapSharingMadeEasy.cs#L48

I don't know what your intention was with this line, but you're unintentionally renaming the whole prefab, not just the name of this piece. You would use `m_name` here instead, as `name` is referencing the name of the `GameObject`, not the `Piece`.

**Comment by yardik** [comment]
Thanks Randy - correct, this was unintentional.
