### ISSUE TITLE
Server side deployment still gives bad map data to clients

### ISSUE THREAD

**Issue by sbtoonz** [yardik/MapSharingMadeEasy#6]
When pressing F7 to receive data it says versions are incompatible but the DLL is copied from 1 source to all machines so it is 1:1 identical 

when using the object to drop pins the interaction works fine

is this meant to be deployed client side or server side or both?

**Comment by yardik** [comment]
All clients need to run the same version. Server side install simply allows you to enforce that all clients are running the same version. If it's getting bad map data between clients, it's definitely version related - or one of the clients is corrupt somehow. Need Logs and more details please.

**Comment by sbtoonz** [comment]
[Info   : Unity Log] MapSharingMadeEasy::Checking Map Sharing Made Easy Version: Server: 2.3.0 client 2.3.0
[Info   : Unity Log] MapSharingMadeEasy::Server forced config: AllowPublicLocations: True
[Info   : Unity Log] MapSharingMadeEasy::Server forced config: SkipPinRange: 25
[Info   : Unity Log] MapSharingMadeEasy::Map data had no sender. Rejecting.
[Error  : Unity Log] cachedPath set to D:\SteamLibrary\steamapps\common\Valheim\BepInEx\plugins\..\cache\torin_78301514_ExploreMapSave.dat

deployment is unable to save my file ?

**Comment by sbtoonz** [comment]
not sure why there is 2x periods after plugins..

**Comment by sbtoonz** [comment]
In touch to this I am curious if it is because I have an uncommon install strategy where C:\ isnt my install drive therefore causing some kind of write problem 
because the \cache\ folder doesnt exist in my plugins

**Comment by sbtoonz** [comment]
2 periods are for subdir i didnt think windows took commands like that for navigation i am to used to linux 

clearing my cache folder from old map versions and letting mapsharingmadeeasy overwrite the cache file is seeming to work I am no longer getting that odd error when trying to share my map data

**Comment by yardik** [comment]
Hey, my mod doesn't write any files etc. Also this line: torin_78301514_ExploreMapSave.dat is from another mod - not mine.
